Spot: improved modularity and made CCN_SPOT_SC1 compatible with BOSDYN_SPOT again.
The interface between BOSDYN_SPOT and sensor configs can be considered more or less stable now.

diff --git a/submitted_models/bosdyn_spot/scripts/install_in_local_fuel_cache b/submitted_models/bosdyn_spot/scripts/install_in_local_fuel_cache
--- a/submitted_models/bosdyn_spot/scripts/install_in_local_fuel_cache
+++ b/submitted_models/bosdyn_spot/scripts/install_in_local_fuel_cache
@@ -4,19 +4,19 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
 # Install the model in local Ignition Fuel cache so that it is available even before being uploaded to Fuel by Open Robotics.
 
-path="${DIR}/../../../../../install/share/ctu_cras_norlab_marv_sensor_config_1"
+path="${DIR}/../../../../../install/share/bosdyn_spot"
 if [ ! -d "$path" ]; then
   path="$1"
 fi
 
 if [ ! -d "$path" ]; then
-  echo "ERROR: Provide a path to the ctu_cras_norlab_marv_sensor_config_1 folder in either install/share or devel/share as an argument to this script." >&2
+  echo "ERROR: Provide a path to the bosdyn_spot folder in either install/share or devel/share as an argument to this script." >&2
   exit 1
 fi
 
 path="$(realpath "$path")"
 
-cache_path="${IGN_FUEL_CACHE_PATH:-${HOME}/.ignition/fuel}/fuel.ignitionrobotics.org/openrobotics/models/ctu_cras_norlab_marv_sensor_config_1/1"
+cache_path="${IGN_FUEL_CACHE_PATH:-${HOME}/.ignition/fuel}/fuel.ignitionrobotics.org/openrobotics/models/bosdyn_spot/1"
 mkdir -p "$cache_path"
 
 for f in model.sdf model.config meshes textures; do
