Spot: Downgraded model.sdf to SDF 1.6.

diff --git a/submitted_models/bosdyn_spot/scripts/update_robot_sdf b/submitted_models/bosdyn_spot/scripts/update_robot_sdf
--- a/submitted_models/bosdyn_spot/scripts/update_robot_sdf
+++ b/submitted_models/bosdyn_spot/scripts/update_robot_sdf
@@ -17,9 +17,13 @@ for file in "${MODEL_DIR}/config/model/common.yaml" "${MODEL_DIR}/config/model/i
   config="${config} $("${DIR}/yaml_to_xacro_args" "$file")"
 done
 
+sdf8_version="$(ign sdf --versions | grep '^8')" || true
+[ -z "$sdf8_version" ] && echo "libsdformat8 not found. It is required to update this robot's SDF. Please install libsdformat8-dev and try again." >&2 && exit 1
+echo "Found libsdformat ${sdf8_version}" >&2
+
 echo -e "Rendering Ignition Gazebo SDF of $(basename "$(realpath "$MODEL_DIR")") with the following Xacro arguments:\n${config}" "$@" >&2
 rosrun xacro xacro "${MODEL_DIR}/urdf/spot.urdf.xacro" ${config} "$@" > "${OUTPUT_FILE}.urdf"
-ign sdf -p "${OUTPUT_FILE}.urdf" | "${DIR}/high_precision_constants.py" - > "${OUTPUT_FILE}"
+ign sdf --force-version "$sdf8_version" -p "${OUTPUT_FILE}.urdf" | "${DIR}/high_precision_constants.py" - > "${OUTPUT_FILE}"
 
 "${DIR}/clean_sdf" "${OUTPUT_FILE}"
 # fix resource paths
