Updated scripts and example rviz file.

diff --git a/submitted_models/explorer_spot_sensor_config_1/scripts/update_robot_sdf b/submitted_models/explorer_spot_sensor_config_1/scripts/update_robot_sdf
--- a/submitted_models/explorer_spot_sensor_config_1/scripts/update_robot_sdf
+++ b/submitted_models/explorer_spot_sensor_config_1/scripts/update_robot_sdf
@@ -20,10 +20,13 @@ for file in "${BASE_MODEL_DIR}/config/model/common.yaml" "${BASE_MODEL_DIR}/conf
   [ -f "$file" ] && config="${config} $("${BASE_MODEL_DIR}/scripts/yaml_to_xacro_args" "$file")"
 done
 
+sdf8_version="$(ign sdf --versions | grep '^8')" || true
+[ -z "$sdf8_version" ] && echo "libsdformat8 not found. It is required to update this robot's SDF. Please install libsdformat8-dev and try again." >&2 && exit 1
+echo "Found libsdformat ${sdf8_version}" >&2
+
 echo -e "Rendering Ignition Gazebo SDF of $(basename "$(realpath "$MODEL_DIR")") with the following Xacro arguments:\n${config}" "$@" >&2
 rosrun xacro xacro "${MODEL_DIR}/urdf/spot.urdf.xacro" ${config} "$@" > "${OUTPUT_FILE}.urdf"
-ign sdf -p "${OUTPUT_FILE}.urdf" | "${BASE_MODEL_DIR}/scripts/high_precision_constants.py" - > "${OUTPUT_FILE}"
-
+ign sdf --force-version "$sdf8_version" -p "${OUTPUT_FILE}.urdf" | "${BASE_MODEL_DIR}/scripts/high_precision_constants.py" - > "${OUTPUT_FILE}"
 
 "${BASE_MODEL_DIR}/scripts/clean_sdf" "${OUTPUT_FILE}"
 
